// =================================================================================
// conv2d_fp16_turing.cu
// Ported from Ampere (SM 8.0) to Turing (SM 7.5 / TU102)
//
// CHANGES FROM AMPERE VERSION:
//  [1] STAGES: 3 -> 2
//      Ampere kernel needed 85.5 KB shared memory (3 stages). Turing's hard limit is
//      64 KB per block. Reducing to 2 stages brings total smem to 57 KB, which fits.
//      A 2-stage (double-buffer) software pipeline is sufficient to hide global-load
//      latency on Turing, whose L2/DRAM latency is ~200-300 cycles — well within
//      a single BK=32 compute phase of ~1024 FMAs.
//
//  [2] cudaAccessPolicyWindow / cudaStreamSetAttribute REMOVED
//      The L2 persistence / access-policy window API (cudaAccessPropertyPersisting,
//      cudaStreamAttributeAccessPolicyWindow) is an Ampere-only feature (SM 8.0+).
//      On Turing the structs compile but the attribute has no effect and the call
//      may silently corrupt stream state. Removed entirely.
//
//  [3] cudaFuncAttributeMaxDynamicSharedMemorySize value corrected
//      The Ampere code requested 87 KB — this call returns cudaErrorInvalidValue on
//      Turing and the subsequent kernel launch silently uses 0 dynamic smem.
//      Now set to the actual 57 KB needed, with cudaFuncAttributePreferredSharedMemory
//      Carveout set to 100 first, which tells the driver to allocate the full 64 KB
//      bank as shared memory (Turing supports this via the same carveout API as
//      Volta/Turing introduced in CUDA 9).
//
//  [4] Sync barrier correctness fixed (STAGES=2 variant)
//      With STAGES=2 the single __syncthreads() per iteration remains correct:
//        - It fires AFTER the prefetch writes to load_idx = (k+1)%2
//        - It ensures those writes are visible before compute reads compute_idx = k%2
//        - Because load_idx != compute_idx for all k, there is no RAW/WAR hazard.
//      A second trailing sync is added at the END of the compute phase so the next
//      iteration's prefetch cannot overwrite a stage still being read when STAGES=2
//      (with STAGES=3 the two-step gap provided implicit separation; with STAGES=2
//      the same slot is re-used every other iteration, requiring an explicit barrier
//      between the read and the next write to that slot).
//
//  [5] HFMA2 usage verified correct — __hfma2 is available since SM 5.3 (Pascal).
//      No FP32 FFMA is generated by __hfma2 on SM 7.5. No changes needed here.
//
//  [6] __launch_bounds__ kept at 1024 — valid on Turing (max 1024 threads/block).
//
// TILE PARAMETERS ARE NOW INDEPENDENTLY TUNABLE (this revision):
//  LOAD_A/LOAD_B originally did a single-shot tile load: the thread-to-data
//  mapping (load_a_row = tid/4, load_b_col = (tid%16)*8, load_b_active =
//  tid<512, etc.) was algebra hardcoded for exactly BM=256/BN=128/BK=32/
//  BLOCK_SIZE=1024 -- every thread loaded exactly one int4 and the numbers
//  happened to divide evenly. They're now grid-stride loops over the tile's
//  int4 count, correct for any BM/BN/BK/BLOCK_SIZE combination (BM, BN
//  multiples of 32; BK, BN multiples of 8) -- same generalization applied to
//  fp16_conv3d.cu, see that file's header comment for the full rationale and
//  the verification approach (a Python simulation of the strided-load index
//  arithmetic across several non-default tile configs).
//
//  BLOCK_SIZE remains DERIVED, not free: every warp covers a fixed 32(M) x
//  32(N) output sub-tile (8 lanes_m * TM=4, 4 lanes_n * TN=8), so the block
//  must contain exactly (BM/32) x (BN/32) warps, giving
//  BLOCK_SIZE = (BM/32)*(BN/32)*32. TM/TN stay fixed at 4/8.
//
//  Overridable via -DCONV2D_BM=.. -DCONV2D_BN=.. -DCONV2D_BK=..
//  -DCONV2D_STAGES=.. (see ../../setup.py's autotune_kernel_tile()). The
//  CONV2D_ prefix avoids colliding with fp16_conv3d.cu's own, independent
//  CONV3D_BM etc. -- extension-wide compile flags apply to every .cu file in
//  setup.py's sources list, so distinct prefixes are required for both files
//  to be separately overridable without cross-talk.
//
//  Defaults below (BM=256/BN=128/BK=32/STAGES=2) are unchanged from the
//  previous revision -- this is a structural generalization, not a retune.
// =================================================================================

#include <cstdio>
#include <cstdint>
#include <cassert>
#include <cuda_runtime.h>
#include <cuda_fp16.h>

// =================================================================================
// Part 1: Configuration -- BM/BN/BK/STAGES are independently tunable (see
// header comment); BLOCK_SIZE is derived from BM/BN, not a free parameter.
// =================================================================================

#ifndef CONV2D_BM
#define CONV2D_BM 256   // Block M (Pixels)   -- must be a multiple of 32
#endif
#ifndef CONV2D_BN
#define CONV2D_BN 128   // Block N (Channels) -- must be a multiple of 32
#endif
#ifndef CONV2D_BK
#define CONV2D_BK 32    // Block K (Accumulation axis) -- must be a multiple of 8
#endif
#ifndef CONV2D_STAGES
#define CONV2D_STAGES 2 // Double/triple-buffer depth, >= 2
#endif

#define BM CONV2D_BM
#define BN CONV2D_BN
#define BK CONV2D_BK
#define STAGES CONV2D_STAGES

// Register tile per thread: 4 rows x 8 cols -- FIXED (see header comment)
#define TM 4
#define TN 8

// Shared memory padding to reduce bank conflicts
#define PAD 8

// Derived: one warp per 32x32 output sub-tile, (BM/32)x(BN/32) warps/block.
#define BLOCK_SIZE ((BM / 32) * (BN / 32) * 32)

// Total int4 (8-half) loads needed to fill the BMxBK / BKxBN smem tiles.
#define A_TILE_INT4 (BM * (BK / 8))
#define B_TILE_INT4 (BK * (BN / 8))

// =================================================================================
// Part 2: Kernel
// =================================================================================

__global__ void __launch_bounds__(BLOCK_SIZE) conv2d_fp16_turing(
    const half* __restrict__ input,     // [B, C_in, H_in, W_in]
    const half* __restrict__ weight,    // [C_out, C_in*KH*KW]  (GEMM-layout)
    const half* __restrict__ bias,
    half* __restrict__ output,          // [B, C_out, H_out, W_out]
    int B, int C_in, int H_in, int W_in,
    int C_out, int K_H, int K_W,
    int H_out, int W_out,
    int s_h, int s_w, int p_h, int p_w, int d_h, int d_w)
{
    extern __shared__ char smem_raw[];

    // As: [STAGES][BM][BK + PAD]
    half (*As)[BM][BK + PAD] = reinterpret_cast<half (*)[BM][BK + PAD]>(smem_raw);

    // Bs: [STAGES][BK][BN + PAD]
    half (*Bs)[BK][BN + PAD] = reinterpret_cast<half (*)[BK][BN + PAD]>(
        smem_raw + STAGES * BM * (BK + PAD) * sizeof(half));

    // Accumulators: [TM][TN/2] half2  (each half2 holds 2 output columns)
    half2 accum[TM][TN / 2];
    half2 frag_a[TM / 2];   // TM=4 -> 2 half2s
    half2 frag_b[TN / 2];   // TN=8 -> 4 half2s

    #pragma unroll
    for (int i = 0; i < TM; i++)
        #pragma unroll
        for (int j = 0; j < TN / 2; j++)
            accum[i][j] = __float2half2_rn(0.0f);

    int tid = threadIdx.x;
    int bx  = blockIdx.x;   // Output channel block
    int by  = blockIdx.y;   // Pixel block

    // ------------------------------------------------------------------
    // Thread -> tile mapping. lane_m/lane_n (the 8x4 split of one warp's 32
    // lanes) is fixed by TM=4/TN=8 and independent of BM/BN. warp_m/warp_n
    // (the block's warp grid) depends on how many warps span N, which does
    // depend on BN -- warp_n_count generalizes the old hardcoded "4".
    // ------------------------------------------------------------------
    int warp_id = tid / 32;
    int lane_id = tid % 32;

    int warp_n_count = BN / 32;
    int warp_m = warp_id / warp_n_count;   // 0 .. (BM/32 - 1)
    int warp_n = warp_id % warp_n_count;   // 0 .. (BN/32 - 1)

    int lane_m = lane_id / 4;   // 0..7
    int lane_n = lane_id % 4;   // 0..3

    int thread_m_start = warp_m * 32 + lane_m * TM;   // max BM-4 < BM
    int thread_n_start = warp_n * 32 + lane_n * TN;   // max BN-8 < BN

    int block_pixel_start   = by * BM;
    int block_channel_start = bx * BN;

    int total_pixels = B * H_out * W_out;
    int total_k      = C_in * K_H * K_W;
    int stride_hw    = H_out * W_out;
    int stride_chw   = C_out * stride_hw;

    int max_k_tiles = (total_k + BK - 1) / BK;

    // ==================================================================
    // Helper macros: grid-stride load of one A/B tile into smem stage s at
    // GEMM-K offset k_base. Correct for any BM/BN/BK/BLOCK_SIZE (a thread
    // may visit 0, 1, or several int4 slots depending on how the tile size
    // compares to BLOCK_SIZE). Flat K index decomposes to (c_in, kh, kw).
    // ==================================================================
#define LOAD_A(s, k_base)                                                   \
    do {                                                                     \
        for (int _i = tid; _i < A_TILE_INT4; _i += BLOCK_SIZE) {            \
            int a_row = _i / (BK / 8);                                      \
            int a_col = (_i % (BK / 8)) * 8;                                \
            int4 lv = make_int4(0,0,0,0);                                   \
            half* vd = reinterpret_cast<half*>(&lv);                        \
            int pixel_idx = block_pixel_start + a_row;                      \
            bool valid_pixel = (pixel_idx < total_pixels);                  \
            int kb = (k_base) + a_col;                                      \
            if (valid_pixel && kb < total_k) {                              \
                int p_b_idx = pixel_idx / stride_hw;                        \
                int rem     = pixel_idx % stride_hw;                        \
                int p_h_out = rem / W_out;                                  \
                int p_w_out = rem % W_out;                                  \
                _Pragma("unroll")                                            \
                for (int v = 0; v < 8; ++v) {                               \
                    int ck = kb + v;                                         \
                    if (ck < total_k) {                                      \
                        int tmp = ck;                                        \
                        int kv  = tmp % K_W; tmp /= K_W;                    \
                        int ku  = tmp % K_H;                                 \
                        int kc  = tmp / K_H;                                 \
                        int h_in = p_h_out * s_h - p_h + ku * d_h;         \
                        int w_in = p_w_out * s_w - p_w + kv * d_w;         \
                        if (h_in >= 0 && h_in < H_in && w_in >= 0 && w_in < W_in) \
                            vd[v] = input[((p_b_idx * C_in + kc) * H_in + h_in) * W_in + w_in]; \
                    }                                                        \
                }                                                            \
            }                                                                \
            *reinterpret_cast<int4*>(&As[(s)][a_row][a_col]) = lv;          \
        }                                                                    \
    } while(0)

#define LOAD_B(s, k_base)                                                   \
    do {                                                                     \
        for (int _i = tid; _i < B_TILE_INT4; _i += BLOCK_SIZE) {            \
            int b_row = _i / (BN / 8);                                      \
            int b_col = (_i % (BN / 8)) * 8;                                \
            int gn = block_channel_start + b_col;                          \
            int gk = (k_base) + b_row;                                     \
            int4 lv = make_int4(0,0,0,0);                                   \
            half* vd = reinterpret_cast<half*>(&lv);                        \
            if (gn < C_out && gk < total_k) {                               \
                _Pragma("unroll")                                            \
                for (int v = 0; v < 8; ++v) {                               \
                    int cn = gn + v;                                         \
                    if (cn < C_out)                                          \
                        vd[v] = weight[cn * total_k + gk];                  \
                }                                                            \
            }                                                                \
            *reinterpret_cast<int4*>(&Bs[(s)][b_row][b_col]) = lv;          \
        }                                                                    \
    } while(0)

    // ==================================================================
    // Prologue: fill stage 0
    // ==================================================================
    if (max_k_tiles > 0) {
        LOAD_A(0, 0);
        LOAD_B(0, 0);
        __syncthreads();
    }

    // ==================================================================
    // Main loop -- double-buffered by default (see fp16_conv3d.cu's
    // main-loop comment for why STAGES>2 is over-synchronized but correct).
    // ==================================================================
    for (int k_step = 0; k_step < max_k_tiles; k_step++) {
        int compute_idx = k_step       % STAGES;   // stage to READ
        int load_idx    = (k_step + 1) % STAGES;   // stage to WRITE next tile

        // 1. Prefetch next tile (overlaps with current compute on Turing's
        //    dual-issue units; both smem write paths are independent)
        if (k_step + 1 < max_k_tiles) {
            int next_k = (k_step + 1) * BK;
            LOAD_A(load_idx, next_k);
            LOAD_B(load_idx, next_k);
        }

        // 2. Barrier: makes this iteration's prefetch visible and protects
        //    the stage that will be computed below from concurrent writes.
        __syncthreads();

        // 3. Compute outer product over BK inner steps using HFMA2
        #pragma unroll
        for (int k_inner = 0; k_inner < BK; k_inner++) {

            // Load A column (4 rows) -> 2 half2s
            half a0 = As[compute_idx][thread_m_start + 0][k_inner];
            half a1 = As[compute_idx][thread_m_start + 1][k_inner];
            half a2 = As[compute_idx][thread_m_start + 2][k_inner];
            half a3 = As[compute_idx][thread_m_start + 3][k_inner];
            frag_a[0] = __halves2half2(a0, a1);
            frag_a[1] = __halves2half2(a2, a3);

            // Load B row (8 cols) -> 4 half2s via int4 vectorised smem read
            int4 b_vec = *reinterpret_cast<int4*>(
                &Bs[compute_idx][k_inner][thread_n_start]);
            const half2* b_h2 = reinterpret_cast<const half2*>(&b_vec);
            frag_b[0] = b_h2[0];
            frag_b[1] = b_h2[1];
            frag_b[2] = b_h2[2];
            frag_b[3] = b_h2[3];

            // Outer product — 4 rows × 4 half2 columns = 8 HFMA2 per row
            // __hfma2 maps to HFMA2 PTX on SM 7.5 — no FFMA generated.
            half2 va0 = __half2half2(frag_a[0].x);   // broadcast a0
            half2 va1 = __half2half2(frag_a[0].y);   // broadcast a1
            half2 va2 = __half2half2(frag_a[1].x);   // broadcast a2
            half2 va3 = __half2half2(frag_a[1].y);   // broadcast a3

            #pragma unroll
            for (int j = 0; j < 4; j++) {
                accum[0][j] = __hfma2(va0, frag_b[j], accum[0][j]);
                accum[1][j] = __hfma2(va1, frag_b[j], accum[1][j]);
                accum[2][j] = __hfma2(va2, frag_b[j], accum[2][j]);
                accum[3][j] = __hfma2(va3, frag_b[j], accum[3][j]);
            }
        }

        // 4. FIX [4]: trailing barrier required for STAGES=2 double-buffer.
        //    Ensures every thread has finished reading compute_idx before the
        //    next iteration's prefetch writes back into that same slot.
        __syncthreads();
    }

#undef LOAD_A
#undef LOAD_B

    // ==================================================================
    // Store accumulators to global memory
    // ==================================================================
    #pragma unroll
    for (int i = 0; i < TM; i++) {
        int m_idx = block_pixel_start + thread_m_start + i;
        if (m_idx < total_pixels) {
            int b_idx = m_idx / stride_hw;
            int rem   = m_idx % stride_hw;

            #pragma unroll
            for (int j = 0; j < TN / 2; j++) {
                int n_base = block_channel_start + thread_n_start + j * 2;

                half v0 = accum[i][j].x;
                half v1 = accum[i][j].y;

                if (n_base < C_out) {
                    if (bias) v0 = __hadd(v0, bias[n_base]);
                    output[b_idx * stride_chw + n_base * stride_hw + rem] = v0;
                }
                if (n_base + 1 < C_out) {
                    if (bias) v1 = __hadd(v1, bias[n_base + 1]);
                    output[b_idx * stride_chw + (n_base + 1) * stride_hw + rem] = v1;
                }
            }
        }
    }
}

// =================================================================================
// Part 3: Launcher
// =================================================================================

void launch_conv2d_fp16(
    const void* input, const void* weight, const void* bias, void* output,
    int B, int C_in, int H_in, int W_in,
    int C_out, int K_H, int K_W,
    int H_out, int W_out,
    int stride_h, int stride_w, int pad_h, int pad_w, int dil_h, int dil_w)
{
    const half* input_ptr  = reinterpret_cast<const half*>(input);
    const half* weight_ptr = reinterpret_cast<const half*>(weight);
    const half* bias_ptr   = reinterpret_cast<const half*>(bias);
    half*       output_ptr = reinterpret_cast<half*>(output);

    int m = B * H_out * W_out;
    int n = C_out;

    dim3 block(BLOCK_SIZE);
    dim3 grid((n + BN - 1) / BN,
              (m + BM - 1) / BM);

    // FIX [1]: smem recalculated for STAGES=2
    //   As: 2 * 256 * 40 * 2 = 40960 bytes
    //   Bs: 2 *  32 * 136 * 2 = 17408 bytes
    //   Total: 58368 bytes (~57 KB) — within Turing's 64 KB hard limit
    int as_bytes    = STAGES * BM * (BK + PAD) * sizeof(half);
    int bs_bytes    = STAGES * BK * (BN + PAD) * sizeof(half);
    int total_smem  = as_bytes + bs_bytes;   // 58368 bytes

    // FIX [2]: cudaAccessPolicyWindow / L2 persistence REMOVED.
    //   That API is Ampere (SM 8.0+) only. On Turing it compiles but has no
    //   effect and the stream-attribute call may return an error that was
    //   silently ignored in the original code. Removed entirely.

    // FIX [3]: Correct smem carveout sequence for Turing.
    //   Step A — tell the driver to dedicate as much of the 64 KB bank as
    //             possible to shared memory (pushes L1 to its minimum).
    //   Step B — then request the exact dynamic smem size we need.
    //             On Turing the cap is 64 KB; requesting 58 KB succeeds.
    //             The original 87 KB request would have returned
    //             cudaErrorInvalidValue and the kernel would have launched
    //             with 0 dynamic smem, causing illegal memory accesses.
    // total_smem is a compile-time constant (STAGES/BM/BK/PAD/BN are
    // #defines), so both attributes only need to be set once per process,
    // not on every conv2d call.
    static bool smem_attrs_set = false;
    if (!smem_attrs_set) {
        cudaFuncSetAttribute(conv2d_fp16_turing,
            cudaFuncAttributePreferredSharedMemoryCarveout,
            cudaSharedmemCarveoutMaxShared);   // Step A

        cudaFuncSetAttribute(conv2d_fp16_turing,
            cudaFuncAttributeMaxDynamicSharedMemorySize,
            total_smem);                        // Step B: 58368 bytes
        smem_attrs_set = true;
    }

    conv2d_fp16_turing<<<grid, block, total_smem, 0>>>(
        input_ptr, weight_ptr, bias_ptr, output_ptr,
        B, C_in, H_in, W_in,
        C_out, K_H, K_W, H_out, W_out,
        stride_h, stride_w, pad_h, pad_w, dil_h, dil_w);
}

// =================================================================================
// Part 4: Autotune benchmark harness (opt-in, NOT part of the real build)
//
// Only compiled when -DCMPEXT3_AUTOTUNE_HARNESS is passed -- see
// autotune_kernel_tile() in ../../setup.py. Mirrors fp16_conv3d.cu's harness
// exactly: exercises the real launch_conv2d_fp16 on synthetic data at
// tools/bench.py's Conv2d shape, timed with cudaEvents. Never linked into
// cmpext3.
// =================================================================================
#ifdef CMPEXT3_AUTOTUNE_HARNESS
#include <cstdio>

int main() {
    // tools/bench.py's Conv2d section.
    const int B = 64, C_in = 128, H_in = 128, W_in = 128;
    const int C_out = 64, K_H = 3, K_W = 3;
    const int s = 1, p = 1, dil = 1;
    const int H_out = (H_in + 2 * p - dil * (K_H - 1) - 1) / s + 1;
    const int W_out = (W_in + 2 * p - dil * (K_W - 1) - 1) / s + 1;

    size_t in_elems  = (size_t)B * C_in * H_in * W_in;
    size_t w_elems   = (size_t)C_out * C_in * K_H * K_W;
    size_t out_elems = (size_t)B * C_out * H_out * W_out;

    half *d_in, *d_w, *d_bias, *d_out;
    if (cudaMalloc(&d_in, in_elems * sizeof(half)) != cudaSuccess ||
        cudaMalloc(&d_w, w_elems * sizeof(half)) != cudaSuccess ||
        cudaMalloc(&d_bias, (size_t)C_out * sizeof(half)) != cudaSuccess ||
        cudaMalloc(&d_out, out_elems * sizeof(half)) != cudaSuccess) {
        fprintf(stderr, "cudaMalloc failed: %s\n", cudaGetErrorString(cudaGetLastError()));
        return 1;
    }

    cudaMemset(d_in, 0x3C, in_elems * sizeof(half));   // 0x3C3C == 1.0h
    cudaMemset(d_w, 0x3C, w_elems * sizeof(half));
    cudaMemset(d_bias, 0, (size_t)C_out * sizeof(half));

    const int warmup = 5, iters = 20;
    for (int i = 0; i < warmup; ++i) {
        launch_conv2d_fp16(d_in, d_w, d_bias, d_out,
            B, C_in, H_in, W_in, C_out, K_H, K_W, H_out, W_out,
            s, s, p, p, dil, dil);
    }
    cudaDeviceSynchronize();

    cudaEvent_t start, stop;
    cudaEventCreate(&start);
    cudaEventCreate(&stop);
    cudaEventRecord(start);
    for (int i = 0; i < iters; ++i) {
        launch_conv2d_fp16(d_in, d_w, d_bias, d_out,
            B, C_in, H_in, W_in, C_out, K_H, K_W, H_out, W_out,
            s, s, p, p, dil, dil);
    }
    cudaEventRecord(stop);
    cudaEventSynchronize(stop);

    float ms = 0.0f;
    cudaEventElapsedTime(&ms, start, stop);

    cudaError_t err = cudaGetLastError();
    if (err != cudaSuccess) {
        fprintf(stderr, "CUDA error: %s\n", cudaGetErrorString(err));
        return 1;
    }

    printf("RESULT_MS=%f\n", ms / iters);

    cudaFree(d_in); cudaFree(d_w); cudaFree(d_bias); cudaFree(d_out);
    cudaEventDestroy(start);
    cudaEventDestroy(stop);
    return 0;
}
#endif // CMPEXT3_AUTOTUNE_HARNESS
